linters:
  disable-all: true
  # run 'golangci-lint help linters' to see the list of supported linters
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Enabled, disabled by default
    - asasalint
    - asciicheck
    - bidichk
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - nolintlint
    - perfsprint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - wrapcheck
  fast: false

run:
  timeout: 3m
